### ISSUE TITLE
All dependencies listed as development only

### ISSUE THREAD

**Issue by gtg3vv** [w3reality/three-geo#13]
In the package.json all dependencies are listed as dev. If installing via npm, these are not included with the package itself even though they are used explicitly and required to use three-geo.

At least the packages below should probably be under dependencies, so that users of this package don't have to list them as explicit dependencies when importing.

`These dependencies were not found:

* @mapbox/sphericalmercator in ./node_modules/three-geo/src/index.js
* @mapbox/tile-cover in ./node_modules/three-geo/src/index.js
* @mapbox/tilebelt in ./node_modules/three-geo/src/index.js
* @mapbox/vector-tile in ./node_modules/three-geo/src/index.js
* @turf/area in ./node_modules/three-geo/src/index.js
* @turf/destination in ./node_modules/three-geo/src/index.js
* @turf/helpers in ./node_modules/three-geo/src/index.js
* @turf/intersect in ./node_modules/three-geo/src/index.js
* @turf/transform-translate in ./node_modules/three-geo/src/index.js
* @turf/union in ./node_modules/three-geo/src/index.js
* get-pixels in ./node_modules/three-geo/src/index.js
* pbf in ./node_modules/three-geo/src/index.js
* xhr in ./node_modules/three-geo/src/index.js

To install them, you can run: npm install --save @mapbox/sphericalmercator @mapbox/tile-cover @mapbox/tilebelt @mapbox/vector-tile @turf/area @turf/destination @turf/helpers @turf/intersect @turf/transform-translate @turf/union get-pixels pbf xhr
`

I'm happy to make a pr for this, but the solution is just the above code which will populate dependencies.

**Comment by j-devel** [comment]
Thanks for the report!

> even though they are used explicitly and required to use three-geo.

I would like to make it clear that the packages you have listed are required *only in development* (when building .min.js files under the *dist/* directory using WebPack) and not required when using the min.js files *in production*.

Following the above intention, I do not agree to include the listed packages in the non-dev dependency section.

However, I think the "Via the ES6 module system" item in the current [setup section](https://github.com/w3reality/three-geo#setup) is then really misleading.   It should be removed since this sort of es-import usage is highly limited to the development stage.  (I suspect you raised this issue due to the description?)

So I would suggest that we make such an edit in readme.

**Comment by gtg3vv** [comment]
Thanks for the quick response. Yes that is why it arose. If trying to use the package as an npm module (which seems to be what the readme indicates) it will fail. I try to avoid including scripts directly at all costs, but this would require the changes above. I think that the es6 section can just be removed since there is already a development section farther down.

**Comment by j-devel** [comment]
> Anyone that uses this as a module will need those dependencies

Yes, that's a good point.  Actually, to meet this demand, we already have `dist/three-geo.esm.min.js`, which is supposed to be consumed (without dependencies!) by the user as
```
import ThreeGeo from 'dist/three-geo.esm.min.js';
```
But, unfortunately, this is broken now.  (The .esm.min.js file here is currently configured only for NodeJs es-module emulation and not for es6-importing in browsers.) I will make a quick fix about the breakage, and then let's think about how we can improve the readme (care to make a PR?).

**Comment by j-devel** [comment]
I think using `three-geo.esm.js` should solve the loading issue now. Thanks for the report!
