### ISSUE TITLE
Support for flat terrain without excessive geometry data

### ISSUE THREAD

**Issue by samipe** [w3reality/three-geo#19]
Hello,

There is an example for a flat terrain, but the implementation is pretty crude - just reseting each vertice's z-position. Could we instead have an option where the PlaneGeometry is not extruded at all but instead consists of 4 vertices? That would greatly help with performance.

**Comment by j-devel** [comment]
Thanks for the feedback!

> an option where the PlaneGeometry is not extruded at all but instead consists of 4 vertices

I would like to keep the API and internal implementation simple.  In this case, rather than adding such an option, can it be solved as post-processing?

We can follow [this example](https://w3reality.github.io/three-geo/examples/heightmaps/index.io.html), where we are composing a sparse `THREE.LineSegments` representation of terrain parts (in blue).  Using the same parameters (`tile` and `proj` in 

https://github.com/w3reality/three-geo/blob/dd251693b1463fcdee4c11a089fabadb29da640d/examples/heightmaps/index.js#L106-L109

), instead, we could compose a `PlaneGeometry` textured with the satellite material.

**Comment by samipe** [comment]
Hi, thank you, will take a look at that!
