### ISSUE TITLE
getTerrainRgb returns Promise { <state>: "rejected" }

### ISSUE THREAD

**Issue by JonThom** [w3reality/three-geo#25]
**Problem:**

the `getTerrainRgb` method returns a rejected Promise

I'm calling the following inside a useEffect() React hook:

```
const ioToken = <mytoken>
const tgeo = new ThreeGeo({
                    tokenMapbox: ioToken,
});

async function fetchGeo() {
    const terrain = await tgeo.getTerrainVector(
                        [0.0, 0.0], // [lat, lng]
                        1.0,               // radius of bounding circle (km)
                        13)               // zoom resolution
    fgRef.current.scene().add(terrain)
                    };               

fetchGeo();
```    

**what happens**
The `getTerrainRgb` method returns a rejected Promise

**additional comments**
The fgRef.current.scene().add() method is from [react-force-graph](https://github.com/vasturiano/react-force-graph).

I've checked that the mapbox API token is valid.

Any ideas why it's not working?

**Comment by j-devel** [comment]
Tried the [simple-viewer](https://github.com/w3reality/three-geo/blob/master/examples/simple-viewer/index.html) example using your parameters:
```
        //const terrain = await tgeo.getTerrainRgb(
        const ret = tgeo.getTerrainRgb(
            [0.0, 0.0], // [lat, lng]
            1.0,        // radius of bounding circle (km)
            13);        // zoom resolution
        const terrain = await ret;
        console.log('ret', ret);
```
However I cannot reproduce the reported `Promise { <state>: "rejected" }`. (One satellite png seems not available for this particular coordinates, though).

![Screen Shot 2020-10-17 at 14 50 36](https://user-images.githubusercontent.com/38098238/96331655-3161f780-1089-11eb-991b-bf7c04a64f85.png)

**Comment by JonThom** [comment]
@j-devel thanks for trying to reproduce the error. 
I have tried with the coordinates given in the readme as well, with the same error.
So it suggests that the error may arise due to being called inside a React hook. I'll try to debug some more and let you know if I find anything.

**Comment by Cobertos** [comment]
I'm getting the same issue. It's really hard because it looks like the error that's thrown is `null`

![image](https://user-images.githubusercontent.com/6759176/100613002-d820f100-32e1-11eb-9b0b-83cf68647d64.png)

So I prettified the `three-geo.esm.js` file. It looks like [it's supposed to be rejecting `null`](https://github.com/w3reality/three-geo/blob/v1.4.2/src/index.js#L1187-L1188) and that the `console.error` is being stripped from the final build.

So I added it back myself and was able to get the actual error that's being thrown out of the build

![image](https://user-images.githubusercontent.com/6759176/100613272-45cd1d00-32e2-11eb-9e0b-5f40435f1982.png)


Some suggestions:
* Please don't strip `console.error`s from your builds
* Don't reject `null`, reject with the `err` so at least the external developer can catch it and act on it.
* Final error seems to be coming from [`resolveGetPixels`](https://github.com/w3reality/three-geo/blob/v1.4.2/src/Fetch.js#L134). I'm building this with webpack for a browser with Nuxt, so maybe something about the build environment is triggering the wrong code path?

**Comment by Cobertos** [comment]
Built the library myself and linked it locally and changing `resolveGetPixels` to

```
static async resolveGetPixels() {
        return __getPixelsDom;
        // return Utils.Meta.isNodeJS() ?
        //     await Utils.Meta.nodeRequire(global, 'get-pixels/node-pixels') :
        //     __getPixelsDom; // use the statically imported one
    }
```

fixed it

**Comment by j-devel** [comment]
Thanks @Cobertos for feedback!  

> - Please don't strip console.errors from your builds (looks like this is from drop_console in es-pack-js)

Addressed in https://github.com/w3reality/es-pack-js/commit/d93a7432a261712ed058540066d603ab06ea21df

> - Don't reject null, reject with the err so at least the external developer can catch it and act on it.
> - Final error seems to be coming from resolveGetPixels. I'm building this with webpack for a browser with Nuxt, so maybe something about the build environment is triggering the wrong code path?

Fixed in cda26f3. The latest v1.4.3 build in [dist](https://github.com/w3reality/three-geo/tree/master/dist) should just work as far as you use them in browsers.
 
For NodeJS users, I've introduced [a new flag option](https://github.com/w3reality/three-geo#note-nodejs) instead of implicitly relying on the crude `isNodeJS()` method.

**Comment by j-devel** [comment]
@JonThom We've come up to a solution in v1.4.3.  Does it solve your case?

**Comment by JonThom** [comment]
@j-devel I can see in the console that the Promise is no longer rejected, so yes, I consider it solved!
(I didn't reply earlier because I encountered another issue - probably not from three-geo - preventing the addition of the terrain to the scene.)
Thanks to @Cobertos for the pro debugging and to @j-devel for the fix!
