### ISSUE TITLE
Change mapbox API endpoint?

### ISSUE THREAD

**Issue by Cobertos** [w3reality/three-geo#26]
It looks like the URIs in `getUriMapbox()` are hardcoded. It would be really nice if they could be customized to use, say, a custom style, like `https://api.mapbox.com/styles/v1/cobertos/ckg6pj7f52ixh19pnzt7ix48z/tiles/256/{z}/{x}/{y}`

**Comment by Cobertos** [comment]
Oh I see, you can just, pass it into `apiVector`, `apiRgb`, or `apiSatellite` in the `ThreeGeo` constructor.

**Comment by j-devel** [comment]
> It would be really nice if they could be customized to use, say, a custom style, like https://api.mapbox.com/styles/v1/cobertos/ckg6pj7f52ixh19pnzt7ix48z/tiles/256/{z}/{x}/{y}

Indeed!

> Oh I see, you can just, pass it into apiVector, apiRgb, or apiSatellite in the ThreeGeo constructor.

For now, I don't think that would work in this case. For example, if we experiment with [the yet undocumented API](https://github.com/w3reality/three-geo/blob/cda26f3505f4b3dd93927c45daba7cc5546a3387/src/index.js#L241) `setApiSatellite()` (which currently does the same thing above):
```
const api = 'https://api.mapbox.com/styles/v1/cobertos/ckg6pj7f52ixh19pnzt7ix48z/tiles/256';
tgeo.setApiSatellite(api);
...
const terrain  = await tgeo.getTerrainRgb(...);
```
`tgeo` just ends up having [a complaint](https://github.com/w3reality/three-geo/blob/cda26f3505f4b3dd93927c45daba7cc5546a3387/src/models/fetch.js#L51) from `getUriCustom()`.

I think the expected behavior is sending a request to something like `${api}/${zoompos.join('/')}${res}?access_token=${token}` (which is similar to [this line](https://github.com/w3reality/three-geo/blob/cda26f3505f4b3dd93927c45daba7cc5546a3387/src/models/fetch.js#L79)).

If anybody ever got this "feature" working, a PR will be really appreciated.
