### ISSUE TITLE
Loading custom DEM data (GeoTIFF) instead of Mapbox data

### ISSUE THREAD

**Issue by lalprakash** [w3reality/three-geo#48]
Is there a way wherein we can add a custom layer with elevation data instead of the mapbox satellite data. For example, if we have a DEM Geotiff  that is routed through the geoserver as tiled layer, can we make use of it instead of the mapbox satellite imagery?

**Comment by j-devel** [comment]
> add a custom layer with elevation data

No out-of-box solutions, but I think this would be possible starting with [this API endpoint issue](https://github.com/w3reality/three-geo/issues/26)

Challenges are

- replace the API endopoint (the above issue),
- decode GeoTIFF in browser somehow, and
- use the new elevation data (instead of rgb DEM) by modifying [src/models/rgb.js](https://github.com/w3reality/three-geo/blob/master/src/models/rgb.js).

**Comment by lalprakash** [comment]
Thanks for the response.

Seems like the right direction. Will update you with the exact steps once I try it.
